<?php include('header.php'); ?>

<div id="m">
	<i id="b" class="fa fa-book"></i>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate, error ex modi illum saepe? Fugit impedit pariatur unde est voluptate reprehenderit autem ipsam a repellendus soluta. Porro, veniam, pariatur consectetur accusantium illum unde numquam aperiam quo? Amet, esse, totam saepe omnis itaque sit ipsa dicta libero. Asperiores, dicta, distinctio esse laboriosam voluptas vel exercitationem pariatur id rerum consequuntur tempore quis natus? Tenetur, facere, mollitia asperiores facilis illo sint ad aut sed ratione a deserunt eaque enim numquam nam iusto? Quod, ipsam, impedit assumenda delectus ullam quibusdam quae doloremque minima aliquid libero nobis sit itaque culpa. Iure, hic quibusdam quo odit magni excepturi perspiciatis. Excepturi, nemo ad suscipit alias in eius quisquam tenetur iusto dolorum. At, non, hic, placeat, excepturi veritatis architecto vel consequuntur iste quibusdam voluptates unde dignissimos incidunt rem aut aperiam quae recusandae molestias dolore harum vero ullam fugiat illum reiciendis optio sunt saepe debitis? Ea, ex, ratione ut nostrum necessitatibus alias quod fugiat accusamus repudiandae at rem nisi eius! Necessitatibus, aliquam, quo, obcaecati quasi nemo nesciunt minus ex reiciendis accusamus assumenda voluptatem iste ducimus. Molestias, maiores, nulla, cumque, ipsum nemo tempora quia commodi saepe earum omnis odit beatae repellendus. Explicabo, placeat suscipit molestiae aut. Quasi, perferendis possimus ipsum.
	</p>
	<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima, ut numquam quis saepe asperiores mollitia corporis alias nisi magnam quia. Explicabo reiciendis ipsam odit deleniti debitis fugit numquam tenetur. Fugiat, nam, aspernatur excepturi hic nesciunt eveniet eaque atque facere dolor beatae animi quod incidunt numquam veritatis odit eligendi tempora impedit pariatur ex adipisci ducimus iste magni vitae enim rem esse itaque. Culpa, harum alias hic repellendus earum maiores eius officia impedit voluptatum reiciendis cumque pariatur quasi at eum iusto nisi velit perspiciatis nemo magnam aperiam animi repellat qui dolorem distinctio dolor expedita enim dolorum deserunt fugiat nam. Magni, facilis, repellendus ipsa veritatis suscipit voluptates cum ratione a nemo ut corporis illo laudantium vitae quas accusamus nulla incidunt adipisci eius fuga cumque officiis non repellat aspernatur reprehenderit cupiditate praesentium nostrum ea et rerum dolor. Ipsam, porro, earum! Repellat, minus, enim ad dignissimos culpa doloremque blanditiis eum cum repellendus dolor. Ipsam excepturi deserunt itaque omnis! Voluptatem, quidem, soluta vero nemo perferendis ex enim! Dignissimos, quasi, voluptates ipsa voluptatibus culpa quae commodi fuga obcaecati quaerat aspernatur. Provident, eum delectus esse sequi molestias eveniet reiciendis dolorum modi beatae voluptas enim blanditiis adipisci eius magnam aut nostrum earum commodi assumenda temporibus ipsum tempora explicabo culpa corporis ipsa nulla reprehenderit asperiores quas distinctio iusto repellat mollitia nemo doloribus voluptatum veritatis dolorem doloremque dolore! Quis, ad, sequi, asperiores, nam quia vero commodi fuga suscipit doloribus iste ea tempore libero quam nihil alias neque deserunt! Quisquam, in dolorum velit consectetur officiis asperiores necessitatibus error pariatur impedit quos eos aliquam veritatis illum rem voluptate id animi maxime quibusdam excepturi eaque numquam commodi nobis quaerat corrupti aut aspernatur perspiciatis deserunt modi nulla. Ipsum, quidem harum natus temporibus iusto vitae quia autem quos officiis veritatis. Praesentium officiis cupiditate perferendis. Nam ullam culpa sapiente rem a nemo tempore adipisci quaerat illum quidem.
	</p>
</div>

<?php include('footer.php'); ?>